import frappeUIPreset from 'frappe-ui/tailwind'

export default {
  presets: [frappeUIPreset],
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './node_modules/frappe-ui/src/**/*.{vue,js,ts,jsx,tsx}',
    '../node_modules/frappe-ui/src/**/*.{vue,js,ts,jsx,tsx}',
    './node_modules/frappe-ui/frappe/**/*.{vue,js,ts,jsx,tsx}',
    '../node_modules/frappe-ui/frappe/**/*.{vue,js,ts,jsx,tsx}',
  ],
  safelist: [
    '!text-black-600',
    '!text-gray-700',
    '!text-blue-600',
    '!text-green-700',
    '!text-red-600',
    '!text-pink-600',
    '!text-orange-600',
    '!text-amber-600',
    '!text-yellow-600',
    '!text-cyan-600',
    '!text-teal-600',
    '!text-violet-600',
    '!text-purple-600',
    '!text-ink-gray-2',
    '!text-ink-gray-4',
    '!text-ink-gray-5',
    '!text-ink-gray-7',
    '!text-ink-gray-9',
    '!text-sm',
    '!bg-surface-gray-1',
    '!bg-surface-gray-2',
    '!bg-surface-gray-3',
    '!bg-surface-gray-4',
    '!bg-surface-gray-5',
    '!bg-surface-modal',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
